// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Minimal projection of the Agentic Substrate control-plane API, extracted
// mechanically from pkg/proto/ateapipb/ateapi.proto of the deployed Substrate
// integration (revision abe771016ae50264d6018885a910fdbbd7a4f0de). Only the
// RPCs below and the message closure they need are kept; messages appear in
// their source order, and message, RPC, field names and field numbers are
// verbatim from that revision, apart from the go_package option and the
// omitted fields marked reserved below. Do not extend this file by hand:
// refresh it by re-extracting from a new revision instead. See SOURCE.md for
// provenance, the annotations exception and the refresh procedure.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v4.25.3
// source: pkg/substrate/internal/ateapipb/ateapi.proto

package ateapipb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ResourceMetadata holds the common fields carried by every Substrate resource.
type ResourceMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// atespace is the namespace the resource belongs to. Empty for global-scoped
	// resources. Caller-specified at creation and immutable thereafter.
	//
	// Atespaced resources should add `+k8s:subfield(atespace)=+k8s:required`
	// Non-atespaced resources should add `+k8s:subfield(atespace)=+k8s:forbidden`
	// +k8s:optional
	// +k8s:format=k8s-short-name
	// +k8s:immutable
	Atespace string `protobuf:"bytes,1,opt,name=atespace,proto3" json:"atespace,omitempty"`
	// name is the resource's name, unique within its atespace (or globally, for
	// global-scoped resources). Caller-specified at creation and immutable thereafter.
	//
	// +k8s:required
	// +k8s:format=k8s-short-name
	// +k8s:immutable
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// uid is a server-assigned, globally unique identifier for this resource.
	// Immutable throughout the lifecycle of the resource.
	//
	// This field is ignored during create operations and used as precondition
	// for update operations.
	//
	// +k8s:optional
	// +k8s:format=k8s-uuid
	// +k8s:immutable
	Uid string `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	// annotations stores opaque caller-provided key-value metadata. Actor updates
	// replace the entire map; omitting it clears existing annotations.
	//
	// +k8s:optional
	// +k8s:mapType=atomic
	// +k8s:mutable
	Annotations   map[string]string `protobuf:"bytes,7,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceMetadata) Reset() {
	*x = ResourceMetadata{}
	mi := &file_pkg_substrate_internal_ateapipb_ateapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceMetadata) ProtoMessage() {}

func (x *ResourceMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_substrate_internal_ateapipb_ateapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceMetadata.ProtoReflect.Descriptor instead.
func (*ResourceMetadata) Descriptor() ([]byte, []int) {
	return file_pkg_substrate_internal_ateapipb_ateapi_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceMetadata) GetAtespace() string {
	if x != nil {
		return x.Atespace
	}
	return ""
}

func (x *ResourceMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceMetadata) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ResourceMetadata) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type Actor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Common resource metadata: atespace, name, uid, version, timestamps.
	//
	// +k8s:required
	// +k8s:subfield(atespace)=+k8s:required
	Metadata *ResourceMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// TODO: replace with full actor_template spec if we decide to make each Actor self-contained.
	// +k8s:required
	// +k8s:subfield(atespace)=+k8s:required
	// +k8s:mutable
	ActorTemplate *ObjectRef `protobuf:"bytes,4,opt,name=actor_template,json=actorTemplate,proto3" json:"actor_template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Actor) Reset() {
	*x = Actor{}
	mi := &file_pkg_substrate_internal_ateapipb_ateapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Actor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Actor) ProtoMessage() {}

func (x *Actor) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_substrate_internal_ateapipb_ateapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Actor.ProtoReflect.Descriptor instead.
func (*Actor) Descriptor() ([]byte, []int) {
	return file_pkg_substrate_internal_ateapipb_ateapi_proto_rawDescGZIP(), []int{1}
}

func (x *Actor) GetMetadata() *ResourceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Actor) GetActorTemplate() *ObjectRef {
	if x != nil {
		return x.ActorTemplate
	}
	return nil
}

// ObjectRef references a Substrate resource by its (atespace, name) identity.
type ObjectRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The atespace of the referenced resource. This field should be empty if the
	// target resource is global-scoped, but references to objects in the same
	// atespace as the referrer must still populate this field.
	//
	// References to atespaced resources should add `+k8s:subfield(atespace)=+k8s:required`
	// References to non-atespaced resources should add `+k8s:subfield(atespace)=+k8s:forbidden`
	// +k8s:optional
	// +k8s:format=k8s-short-name
	Atespace string `protobuf:"bytes,1,opt,name=atespace,proto3" json:"atespace,omitempty"`
	// The name of the referenced resource. This field is required.
	//
	// +k8s:required
	// +k8s:format=k8s-short-name
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectRef) Reset() {
	*x = ObjectRef{}
	mi := &file_pkg_substrate_internal_ateapipb_ateapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectRef) ProtoMessage() {}

func (x *ObjectRef) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_substrate_internal_ateapipb_ateapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectRef.ProtoReflect.Descriptor instead.
func (*ObjectRef) Descriptor() ([]byte, []int) {
	return file_pkg_substrate_internal_ateapipb_ateapi_proto_rawDescGZIP(), []int{2}
}

func (x *ObjectRef) GetAtespace() string {
	if x != nil {
		return x.Atespace
	}
	return ""
}

func (x *ObjectRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ActorTemplate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Common resource metadata: atespace, name, uid, version, timestamps.
	//
	// +k8s:required
	// +k8s:subfield(atespace)=+k8s:required
	Metadata      *ResourceMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorTemplate) Reset() {
	*x = ActorTemplate{}
	mi := &file_pkg_substrate_internal_ateapipb_ateapi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorTemplate) ProtoMessage() {}

func (x *ActorTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_substrate_internal_ateapipb_ateapi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorTemplate.ProtoReflect.Descriptor instead.
func (*ActorTemplate) Descriptor() ([]byte, []int) {
	return file_pkg_substrate_internal_ateapipb_ateapi_proto_rawDescGZIP(), []int{3}
}

func (x *ActorTemplate) GetMetadata() *ResourceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetActorTemplateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// +k8s:required
	// +k8s:subfield(atespace)=+k8s:required
	ActorTemplate *ObjectRef `protobuf:"bytes,1,opt,name=actor_template,json=actorTemplate,proto3" json:"actor_template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActorTemplateRequest) Reset() {
	*x = GetActorTemplateRequest{}
	mi := &file_pkg_substrate_internal_ateapipb_ateapi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActorTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActorTemplateRequest) ProtoMessage() {}

func (x *GetActorTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_substrate_internal_ateapipb_ateapi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActorTemplateRequest.ProtoReflect.Descriptor instead.
func (*GetActorTemplateRequest) Descriptor() ([]byte, []int) {
	return file_pkg_substrate_internal_ateapipb_ateapi_proto_rawDescGZIP(), []int{4}
}

func (x *GetActorTemplateRequest) GetActorTemplate() *ObjectRef {
	if x != nil {
		return x.ActorTemplate
	}
	return nil
}

type GetActorRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// +k8s:required
	// +k8s:subfield(atespace)=+k8s:required
	Actor         *ObjectRef `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActorRequest) Reset() {
	*x = GetActorRequest{}
	mi := &file_pkg_substrate_internal_ateapipb_ateapi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActorRequest) ProtoMessage() {}

func (x *GetActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_substrate_internal_ateapipb_ateapi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActorRequest.ProtoReflect.Descriptor instead.
func (*GetActorRequest) Descriptor() ([]byte, []int) {
	return file_pkg_substrate_internal_ateapipb_ateapi_proto_rawDescGZIP(), []int{5}
}

func (x *GetActorRequest) GetActor() *ObjectRef {
	if x != nil {
		return x.Actor
	}
	return nil
}

var File_pkg_substrate_internal_ateapipb_ateapi_proto protoreflect.FileDescriptor

const file_pkg_substrate_internal_ateapipb_ateapi_proto_rawDesc = "" +
	"\n" +
	",pkg/substrate/internal/ateapipb/ateapi.proto\x12\x06ateapi\"\xf3\x01\n" +
	"\x10ResourceMetadata\x12\x1a\n" +
	"\batespace\x18\x01 \x01(\tR\batespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\tR\x03uid\x12K\n" +
	"\vannotations\x18\a \x03(\v2).ateapi.ResourceMetadata.AnnotationsEntryR\vannotations\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x04\x10\x05J\x04\b\x05\x10\x06J\x04\b\x06\x10\a\"\x89\x01\n" +
	"\x05Actor\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.ateapi.ResourceMetadataR\bmetadata\x128\n" +
	"\x0eactor_template\x18\x04 \x01(\v2\x11.ateapi.ObjectRefR\ractorTemplateJ\x04\b\x05\x10\x06J\x04\b\x06\x10\aJ\x04\b\a\x10\b\";\n" +
	"\tObjectRef\x12\x1a\n" +
	"\batespace\x18\x01 \x01(\tR\batespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"o\n" +
	"\rActorTemplate\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.ateapi.ResourceMetadataR\bmetadataJ\x04\b\x02\x10\x03J\x04\b\x03\x10\x04J\x04\b\x04\x10\x05J\x04\b\x05\x10\x06J\x04\b\x06\x10\aJ\x04\b\a\x10\bJ\x04\b\b\x10\t\"S\n" +
	"\x17GetActorTemplateRequest\x128\n" +
	"\x0eactor_template\x18\x01 \x01(\v2\x11.ateapi.ObjectRefR\ractorTemplate\":\n" +
	"\x0fGetActorRequest\x12'\n" +
	"\x05actor\x18\x01 \x01(\v2\x11.ateapi.ObjectRefR\x05actor2\x8d\x01\n" +
	"\aControl\x124\n" +
	"\bGetActor\x12\x17.ateapi.GetActorRequest\x1a\r.ateapi.Actor\"\x00\x12L\n" +
	"\x10GetActorTemplate\x12\x1f.ateapi.GetActorTemplateRequest\x1a\x15.ateapi.ActorTemplate\"\x00BUZSgithub.com/kubernetes-sigs/alibaba-cloud-csi-driver/pkg/substrate/internal/ateapipbb\x06proto3"

var (
	file_pkg_substrate_internal_ateapipb_ateapi_proto_rawDescOnce sync.Once
	file_pkg_substrate_internal_ateapipb_ateapi_proto_rawDescData []byte
)

func file_pkg_substrate_internal_ateapipb_ateapi_proto_rawDescGZIP() []byte {
	file_pkg_substrate_internal_ateapipb_ateapi_proto_rawDescOnce.Do(func() {
		file_pkg_substrate_internal_ateapipb_ateapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_substrate_internal_ateapipb_ateapi_proto_rawDesc), len(file_pkg_substrate_internal_ateapipb_ateapi_proto_rawDesc)))
	})
	return file_pkg_substrate_internal_ateapipb_ateapi_proto_rawDescData
}

var file_pkg_substrate_internal_ateapipb_ateapi_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_substrate_internal_ateapipb_ateapi_proto_goTypes = []any{
	(*ResourceMetadata)(nil),        // 0: ateapi.ResourceMetadata
	(*Actor)(nil),                   // 1: ateapi.Actor
	(*ObjectRef)(nil),               // 2: ateapi.ObjectRef
	(*ActorTemplate)(nil),           // 3: ateapi.ActorTemplate
	(*GetActorTemplateRequest)(nil), // 4: ateapi.GetActorTemplateRequest
	(*GetActorRequest)(nil),         // 5: ateapi.GetActorRequest
	nil,                             // 6: ateapi.ResourceMetadata.AnnotationsEntry
}
var file_pkg_substrate_internal_ateapipb_ateapi_proto_depIdxs = []int32{
	6, // 0: ateapi.ResourceMetadata.annotations:type_name -> ateapi.ResourceMetadata.AnnotationsEntry
	0, // 1: ateapi.Actor.metadata:type_name -> ateapi.ResourceMetadata
	2, // 2: ateapi.Actor.actor_template:type_name -> ateapi.ObjectRef
	0, // 3: ateapi.ActorTemplate.metadata:type_name -> ateapi.ResourceMetadata
	2, // 4: ateapi.GetActorTemplateRequest.actor_template:type_name -> ateapi.ObjectRef
	2, // 5: ateapi.GetActorRequest.actor:type_name -> ateapi.ObjectRef
	5, // 6: ateapi.Control.GetActor:input_type -> ateapi.GetActorRequest
	4, // 7: ateapi.Control.GetActorTemplate:input_type -> ateapi.GetActorTemplateRequest
	1, // 8: ateapi.Control.GetActor:output_type -> ateapi.Actor
	3, // 9: ateapi.Control.GetActorTemplate:output_type -> ateapi.ActorTemplate
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_substrate_internal_ateapipb_ateapi_proto_init() }
func file_pkg_substrate_internal_ateapipb_ateapi_proto_init() {
	if File_pkg_substrate_internal_ateapipb_ateapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_substrate_internal_ateapipb_ateapi_proto_rawDesc), len(file_pkg_substrate_internal_ateapipb_ateapi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_substrate_internal_ateapipb_ateapi_proto_goTypes,
		DependencyIndexes: file_pkg_substrate_internal_ateapipb_ateapi_proto_depIdxs,
		MessageInfos:      file_pkg_substrate_internal_ateapipb_ateapi_proto_msgTypes,
	}.Build()
	File_pkg_substrate_internal_ateapipb_ateapi_proto = out.File
	file_pkg_substrate_internal_ateapipb_ateapi_proto_goTypes = nil
	file_pkg_substrate_internal_ateapipb_ateapi_proto_depIdxs = nil
}
