controller:
  enabled: true
  replicas: 2

plugin:
  enabled: true

csi:
  disk:
    enabled: true
    controller:
      enabled: true
  nas:
    enabled: true
    controller:
      enabled: true
  oss:
    enabled: true
    controller:
      enabled: true
  local:
    enabled: false
    controller:
      enabled: true

nodePools:
  default:
    pluginname: csi-plugin
    nodeSelectorTerms:
      - matchExpressions:
        - key: type
          operator: NotIn
          values:
            - virtual-kubelet

defaultStorageClass:
  enabled: true

deploy:
  kubeletRootDir: /var/lib/kubelet

  # By default, the controller server does not delete NAS subpaths when DeleteVolume, that means
  # the files created in the volume will remain in the filesystem after PV deleted.
  # You can set "withStorageController" to true in ACK clusters with storage-operator addon installed, 
  # then the controller server will patch a finalizer on NAS subpath-type PV when DeleteVolume 
  # and the storage-controller will handle the cleanup of the subpath in NAS filesystem.
  withStorageController: false

  # Which namespace holds ossfs pods
  fuseNamespace: ack-csi-fuse

  featureGates: ""   # only for alpha feature
  privateCloud: false
  ecsEndpoint: null  # most useful on private cloud

  ack: true  # deployed on managed Alibaba Cloud Container Service for Kubernetes (ACK)
  ecs: true  # use Alibaba Cloud Elastic Compute Service (ECS) for Node
  clusterID: null  # will be injected on installation on ACK
  regionID: null  # useful when deploying on non-ECS, but need to access Alibaba Cloud OpenAPI

  # To access Alibaba Cloud OpenAPI in self-deployed Kubernetes cluster, use a Secret with "id" and "secret" set.
  accessKey:
    enabled: false
    secretName: csi-access-key
    idKey: id # the key of AccessKey id in the k8s Secret
    secretkey: secret # the key of AccessKey secret in the k8s Secret

images:
  registry: registry-cn-hangzhou.ack.aliyuncs.com
  workerRegistry: null  # registry for worker nodes, if different from registry
  controller:
    repo: acs/csi-plugin
    tag: "v1.30.1-242df8a-aliyun"
  plugin:
    repo: acs/csi-plugin
    tag: "v1.30.1-242df8a-aliyun"
  pluginInit:
    repo: acs/csi-plugin
    tag: "v1.30.1-242df8a-aliyun-init"
  localController:
    repo: acs/local-csi-driver
    tag: "v0.1.0"
  localPlugin:
    repo: acs/local-csi-driver
    tag: "v0.1.0"
  externalAttacher:
    repo: acs/csi-attacher
    tag: "v4.5.0-4a01fda6-aliyun"
  externalProvisioner:
    repo: acs/csi-provisioner
    tag: "v3.5.0-e7da67e52-aliyun"
  externalResizer:
    repo: acs/csi-resizer
    tag: "v1.3-e48d981-aliyun"
  externalSnapshotter:
    repo: acs/csi-snapshotter
    tag: "v4.0.0-a230d5b-aliyun"
  externalSnapshotController:
    repo: acs/snapshot-controller
    tag: "v4.0.0-a230d5b-aliyun"
  pluginRegistrar:
    repo: acs/csi-node-driver-registrar
    tag: "v2.9.0-d48d2e0-aliyun"
  ossfs:
    tag: "v1.88.4-d9f3917-aliyun"
    updatedTag: "v1.91.3-d9f3917-aliyun"
