# deployment
csi:
  local:
    enabled: true
  oss:
    controller:
      enabled: false

# daemonset
nodepools:
  default:
    pluginname: csi-plugin-cloud
    nodeSelectorTerms:
      - matchExpressions:
        - key: type
          operator: NotIn
          values:
            - virtual-kubelet
        - key: alibabacloud.com/is-edge-worker
          operator: In
          values:
            - "false"
  edge:
    pluginname: csi-plugin
    csi:
      disk:
        enabled: false
    nodeSelectorTerms:
      - matchExpressions:
        - key: alibabacloud.com/is-edge-worker
          operator: In
          values:
            - "true"
  # other nodepools