apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nas-sts
spec:
  selector:
    matchLabels:
      app: busybox
  serviceName: "busybox"
  replicas: 1
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
        - name: busybox
          image: busybox
          command:
            - sleep
            - "3600"
          volumeMounts:
            - name: nas-pvc
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: nas-pvc
      spec:
        accessModes: [ "ReadWriteMany" ]
        storageClassName: "alicloud-nas-quota-sc"
        resources:
          requests:
            storage: 20Gi