kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nas-csi-pvc-sp
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: alicloud-nas-subpath
  resources:
    requests:
      storage: 20Gi